Class definition sometimes required
The _loc.name() return 'string'. If compiler not take into account copy
elision (ISO/IEC 14882-2003 12.8 par 15), this line may lead to temporary
object creation, so compiler need to control that object 'string' is
constructable here (ISO/IEC 14882-2003 8.5.3 par 5). This require
compiler's access to class 'string' definition; forward declaration of
class 'string' (as was done in stlport/stl/_locale.h via

 # include <stl/_string_fwd.h>

) not enough.
The same thoughts suitable for C++-11 standard too.

Whether problem really happens, depends upon compiler templates
instantiation technique. Unobservable for gcc and VS.
Present for CLang and (possible) Comeau.

Problem is detected by CLang 3.0 and pre-3.1:

../stlport/stl/_locale.h:155:39: error: implicit instantiation of undefined template
      'stlp_std::basic_string<char, stlp_std::char_traits<char>, stlp_std::allocator<char> >'
      _M_throw_on_combine_error(__loc.name());